project_id = "central-campanha"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[db.migrations]
enabled = true

[db.seed]
enabled = false

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://orisee1.github.io/blank-campaign-page/"
additional_redirect_urls = ["http://127.0.0.1:5173/blank-campaign-page/"]
jwt_expiry = 3600
enable_signup = false

[auth.email]
enable_signup = false
enable_confirmations = true
secure_password_change = true

[storage]
enabled = true
file_size_limit = "25MiB"

