import { useMemo, useState } from "react";
import { ArchiveRestore, DatabaseBackup, KeyRound, Lock, MonitorSmartphone, Plus, RefreshCw, Save, Settings, ShieldCheck, Trash2, UserCog, Users, Wifi } from "lucide-react";
import { useApp } from "../context/AppContext";
import type { CollectionName, PermissionAction, UserRecord } from "../types";
import { Modal } from "../components/Modal";
import { createPasswordCredential } from "../lib/auth";
import { getMeta, saveMany, setMeta } from "../lib/db";

type Tab = "identity" | "users" | "roles" | "sync" | "devices" | "backup" | "trash";
const modules = ["dashboard", "people", "processes", "tasks", "calendar", "events", "team", "territory", "documents", "finance", "reports", "reminders", "privacy", "audit", "admin"];
const actions: { key: PermissionAction; label: string }[] = [{ key: "view", label: "Ver" }, { key: "create", label: "Criar" }, { key: "edit", label: "Editar" }, { key: "delete", label: "Excluir" }, { key: "restore", label: "Restaurar" }, { key: "export", label: "Exportar" }, { key: "assign", label: "Atribuir" }, { key: "documents", label: "Dados/Docs" }, { key: "reports", label: "Relatórios" }, { key: "settings", label: "Config." }];
type CredentialMap = Record<string, { salt: string; hash: string }>;

export function AdminPage() {
  const { data, settings, currentUser, pendingCount, online, syncing, updateSettings, createRecord, updateRecord, restore, refresh } = useApp();
  const [tab, setTab] = useState<Tab>("identity");
  const [identity, setIdentity] = useState(settings);
  const [userOpen, setUserOpen] = useState(false);
  const [userForm, setUserForm] = useState({ name: "", username: "", email: "", roleId: "role-volunteer", password: "", regionIds: "" });
  const [passwordOpen, setPasswordOpen] = useState(false);
  const [newPassword, setNewPassword] = useState("");
  const [toast, setToast] = useState("");
  const [restoreFile, setRestoreFile] = useState<File | null>(null);
  const deviceId = localStorage.getItem("central-campanha-device") ?? "browser";
  const trash = useMemo(() => (Object.entries(data) as [CollectionName, { id: string; deletedAt?: string; name?: string; title?: string; description?: string }[]][]).flatMap(([collection, rows]) => rows.filter((row) => row.deletedAt).map((row) => ({ collection, ...row }))), [data]);
  const flash = (message: string) => { setToast(message); setTimeout(() => setToast(""), 2800); };

  const createUser = async (event: React.FormEvent) => {
    event.preventDefault();
    if (data.users.some((item) => item.username.toLowerCase() === userForm.username.trim().toLowerCase())) { flash("Esse nome de usuário já existe."); return; }
    const user = await createRecord("users", { username: userForm.username.trim().toLowerCase(), name: userForm.name.trim(), email: userForm.email, roleId: userForm.roleId, active: true, regionIds: userForm.regionIds.split(",").map((item) => item.trim()).filter(Boolean), teamIds: [], permissionOverrides: {} }, `Usuário ${userForm.username} criado`);
    const credentials = await getMeta<CredentialMap>("user-credentials") ?? {};
    credentials[user.id] = await createPasswordCredential(userForm.password);
    await setMeta("user-credentials", credentials);
    setUserOpen(false); setUserForm({ name: "", username: "", email: "", roleId: "role-volunteer", password: "", regionIds: "" }); flash("Usuário criado com credencial temporária.");
  };

  const changePassword = async (event: React.FormEvent) => {
    event.preventDefault(); if (!currentUser) return;
    const credential = await createPasswordCredential(newPassword);
    if (currentUser.id === "user-master") await setMeta("master-credential", { username: currentUser.username, ...credential });
    else { const credentials = await getMeta<CredentialMap>("user-credentials") ?? {}; credentials[currentUser.id] = credential; await setMeta("user-credentials", credentials); }
    await createRecord("audit", { action: "password", module: "auth", summary: "Senha alterada pelo usuário", deviceId }); setPasswordOpen(false); setNewPassword(""); flash("Senha alterada neste dispositivo. Reconfigure-a no backend antes da produção.");
  };

  const togglePermission = async (roleId: string, module: string, action: PermissionAction) => {
    const role = data.roles.find((item) => item.id === roleId); if (!role || role.id === "role-master") return;
    const current = role.permissions[module] ?? []; const next = current.includes(action) ? current.filter((item) => item !== action) : [...current, action];
    await updateRecord("roles", role.id, { permissions: { ...role.permissions, [module]: next } }, `Permissão ${action} em ${module} alterada para ${role.name}`); flash("Permissão atualizada e auditada.");
  };

  const backup = async () => {
    const payload = { version: 1, exportedAt: new Date().toISOString(), settings, data };
    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `backup-central-campanha-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url);
    await createRecord("audit", { action: "backup", module: "admin", summary: "Backup administrativo exportado", deviceId }); flash("Backup gerado e registrado na auditoria.");
  };
  const restoreBackup = async () => {
    if (!restoreFile) return;
    try { const parsed = JSON.parse(await restoreFile.text()) as { version: number; data: Record<string, unknown[]> }; if (parsed.version !== 1) throw new Error(); for (const collection of Object.keys(data) as CollectionName[]) { const rows = parsed.data[collection]; if (Array.isArray(rows)) await saveMany(collection, rows as never); } await refresh(); setRestoreFile(null); flash("Backup restaurado neste dispositivo."); } catch { flash("Arquivo de backup inválido ou incompatível."); }
  };

  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">CONTROLE DO SISTEMA</p><h1>Administração</h1><p>Identidade, usuários, permissões, segurança e continuidade.</p></div><button className="button ghost" onClick={() => setPasswordOpen(true)}><KeyRound size={17} /> Alterar minha senha</button></header>
    <div className="admin-layout"><nav className="admin-tabs">{[
      ["identity", Settings, "Identidade"], ["users", Users, "Usuários"], ["roles", ShieldCheck, "Funções e permissões"], ["sync", RefreshCw, "Sincronização"], ["devices", MonitorSmartphone, "Dispositivos"], ["backup", DatabaseBackup, "Backup"], ["trash", Trash2, "Lixeira"],
    ].map(([id, Icon, label]) => <button key={String(id)} className={tab === id ? "active" : ""} onClick={() => setTab(id as Tab)}><Icon size={18} />{String(label)}</button>)}</nav>
      <section className="panel admin-content">
        {tab === "identity" && <><header className="panel-header"><div><h2>Identidade da campanha</h2><p>Essas informações aparecem no sistema e nos relatórios.</p></div></header><form className="record-form" onSubmit={async (event) => { event.preventDefault(); await updateSettings(identity); flash("Identidade da campanha atualizada."); }}><div className="form-grid"><label>Nome do sistema<input value={identity.name} onChange={(event) => setIdentity({ ...identity, name: event.target.value })} /></label><label>Nome da candidata<input value={identity.candidateName} onChange={(event) => setIdentity({ ...identity, candidateName: event.target.value })} /></label><label>Cargo<input value={identity.office} onChange={(event) => setIdentity({ ...identity, office: event.target.value })} /></label><label>Estado<input value={identity.state ?? ""} onChange={(event) => setIdentity({ ...identity, state: event.target.value })} /></label><label>Partido <small>opcional</small><input value={identity.party ?? ""} onChange={(event) => setIdentity({ ...identity, party: event.target.value })} /></label><label>Número eleitoral <small>opcional</small><input value={identity.electionNumber ?? ""} onChange={(event) => setIdentity({ ...identity, electionNumber: event.target.value })} /></label><label>Cor principal<input type="color" value={identity.primaryColor} onChange={(event) => setIdentity({ ...identity, primaryColor: event.target.value })} /></label><label>Cor de destaque<input type="color" value={identity.accentColor} onChange={(event) => setIdentity({ ...identity, accentColor: event.target.value })} /></label></div><footer className="modal-actions"><button className="button primary"><Save size={17} /> Salvar configurações</button></footer></form></>}
        {tab === "users" && <><header className="panel-header"><div><h2>Usuários autorizados</h2><p>Não existe cadastro público. Somente administradores criam acessos.</p></div><button className="button primary compact" onClick={() => setUserOpen(true)}><Plus size={17} /> Novo usuário</button></header><div className="responsive-table"><table><thead><tr><th>Usuário</th><th>Função</th><th>Status</th><th>Escopo</th><th>Ações</th></tr></thead><tbody>{data.users.filter((item) => !item.deletedAt).map((user) => <tr key={user.id}><td><div className="person-cell"><span className="avatar small">{user.name.split(" ").map((part) => part[0]).slice(0, 2).join("")}</span><span><strong>{user.name}</strong><small>@{user.username} {user.email && `• ${user.email}`}</small></span></div></td><td><select value={user.roleId} disabled={user.id === "user-master"} onChange={(event) => void updateRecord("users", user.id, { roleId: event.target.value }, `Função do usuário ${user.username} alterada`)}>{data.roles.filter((item) => !item.deletedAt).map((role) => <option value={role.id} key={role.id}>{role.name}</option>)}</select></td><td><span className={`status-badge ${user.active ? "" : "danger"}`}>{user.active ? "Ativo" : "Bloqueado"}</span></td><td>{data.roles.find((role) => role.id === user.roleId)?.scope ?? "—"}</td><td><button className="button tiny" disabled={user.id === "user-master"} onClick={() => void updateRecord("users", user.id, { active: !user.active }, `${user.active ? "Bloqueou" : "Ativou"} usuário ${user.username}`)}>{user.active ? <><Lock size={14} /> Bloquear</> : "Ativar"}</button></td></tr>)}</tbody></table></div></>}
        {tab === "roles" && <><header className="panel-header"><div><h2>Funções e permissões</h2><p>Permissões são aplicadas também às rotas e operações de dados.</p></div></header><div className="role-cards">{data.roles.filter((role) => !role.deletedAt).map((role) => <details key={role.id} open={role.id === "role-volunteer"}><summary><span><strong>{role.name}</strong><small>{role.description} • Escopo: {role.scope}</small></span><UserCog size={18} /></summary><div className="permission-matrix"><table><thead><tr><th>Módulo</th>{actions.map((action) => <th key={action.key}>{action.label}</th>)}</tr></thead><tbody>{modules.map((module) => <tr key={module}><td>{module}</td>{actions.map((action) => <td key={action.key}><input type="checkbox" disabled={role.id === "role-master"} checked={(role.permissions[module] ?? []).includes(action.key)} onChange={() => void togglePermission(role.id, module, action.key)} /></td>)}</tr>)}</tbody></table></div></details>)}</div></>}
        {tab === "sync" && <><header className="panel-header"><div><h2>Sincronização</h2><p>A fila nunca é descartada por falha de conexão.</p></div></header><div className="status-cards"><article><Wifi size={25} /><span><small>Conexão</small><strong>{online ? "Online" : "Offline"}</strong></span></article><article><RefreshCw className={syncing ? "spin" : ""} size={25} /><span><small>Estado</small><strong>{syncing ? "Sincronizando" : pendingCount ? "Aguardando servidor" : "Em dia"}</strong></span></article><article><DatabaseBackup size={25} /><span><small>Fila local</small><strong>{pendingCount} alterações</strong></span></article></div>{!import.meta.env.VITE_API_URL && <div className="admin-warning"><ShieldCheck size={21} /><div><strong>Backend ainda não conectado</strong><p>Os dados permanecem seguros neste dispositivo e disponíveis offline. Para múltiplos usuários e sincronização real, publique o backend e configure o endereço da API no ambiente de produção.</p></div></div>}<button className="button ghost" onClick={() => void refresh()}><RefreshCw size={17} /> Verificar novamente</button></>}
        {tab === "devices" && <><header className="panel-header"><div><h2>Meus dispositivos</h2><p>Sessões reconhecidas para este acesso.</p></div></header><div className="device-card"><MonitorSmartphone size={28} /><span><strong>{navigator.userAgent.includes("Windows") ? "Computador Windows" : "Navegador atual"}</strong><small>ID: {deviceId.slice(0, 12)}… • sessão atual</small></span><span className="status-badge">Ativo</span></div><p className="muted">A revogação remota de outros dispositivos será aplicada pelo backend assim que ele estiver conectado.</p></>}
        {tab === "backup" && <><header className="panel-header"><div><h2>Backup administrativo</h2><p>Exporte um pacote completo ou restaure uma cópia validada.</p></div></header><div className="backup-grid"><article><DatabaseBackup size={32} /><h3>Exportar backup</h3><p>Inclui registros, configurações, permissões e auditoria. Arquivos anexos permanecem no armazenamento local.</p><button className="button primary" onClick={() => void backup()}>Gerar backup JSON</button></article><article><ArchiveRestore size={32} /><h3>Restaurar backup</h3><p>A restauração substitui coleções existentes no dispositivo. Use somente arquivos confiáveis.</p><input type="file" accept="application/json,.json" onChange={(event) => setRestoreFile(event.target.files?.[0] ?? null)} /><button className="button ghost" disabled={!restoreFile} onClick={() => void restoreBackup()}>Restaurar arquivo</button></article></div></>}
        {tab === "trash" && <><header className="panel-header"><div><h2>Lixeira</h2><p>Registros excluídos logicamente podem ser restaurados.</p></div></header>{trash.length === 0 ? <div className="panel-empty"><Trash2 size={34} /><strong>A lixeira está vazia</strong><span>Registros removidos aparecerão aqui.</span></div> : <div className="responsive-table"><table><thead><tr><th>Registro</th><th>Módulo</th><th>Excluído em</th><th /></tr></thead><tbody>{trash.map((row) => <tr key={`${row.collection}-${row.id}`}><td><strong>{row.name ?? row.title ?? row.description ?? row.id}</strong></td><td>{row.collection}</td><td>{row.deletedAt ? new Date(row.deletedAt).toLocaleString("pt-BR") : "—"}</td><td><button className="button tiny" onClick={() => void restore(row.collection, row.id)}><ArchiveRestore size={14} /> Restaurar</button></td></tr>)}</tbody></table></div>}</>}
      </section>
    </div>
    {userOpen && <Modal title="Criar usuário autorizado" description="Defina uma senha temporária e envie-a por um canal seguro." onClose={() => setUserOpen(false)}><form className="record-form" onSubmit={createUser}><div className="form-grid"><label className="span-2">Nome *<input required value={userForm.name} onChange={(event) => setUserForm({ ...userForm, name: event.target.value })} /></label><label>Usuário *<input required value={userForm.username} onChange={(event) => setUserForm({ ...userForm, username: event.target.value })} /></label><label>E-mail<input type="email" value={userForm.email} onChange={(event) => setUserForm({ ...userForm, email: event.target.value })} /></label><label>Função<select value={userForm.roleId} onChange={(event) => setUserForm({ ...userForm, roleId: event.target.value })}>{data.roles.filter((item) => !item.deletedAt).map((role) => <option value={role.id} key={role.id}>{role.name}</option>)}</select></label><label>Senha temporária *<input required type="password" minLength={8} value={userForm.password} onChange={(event) => setUserForm({ ...userForm, password: event.target.value })} /></label><label className="span-2">IDs de regiões permitidas <small>separados por vírgula</small><input value={userForm.regionIds} onChange={(event) => setUserForm({ ...userForm, regionIds: event.target.value })} /></label></div><footer className="modal-actions"><button type="button" className="button ghost" onClick={() => setUserOpen(false)}>Cancelar</button><button className="button primary">Criar usuário</button></footer></form></Modal>}
    {passwordOpen && <Modal title="Alterar minha senha" description="Use pelo menos 10 caracteres e evite reutilizar senhas." onClose={() => setPasswordOpen(false)}><form className="record-form" onSubmit={changePassword}><label>Nova senha<input autoFocus required minLength={10} type="password" value={newPassword} onChange={(event) => setNewPassword(event.target.value)} /></label><footer className="modal-actions"><button type="button" className="button ghost" onClick={() => setPasswordOpen(false)}>Cancelar</button><button className="button primary">Atualizar senha</button></footer></form></Modal>}
    {toast && <div className="toast success">{toast}</div>}
  </div>;
}
