import { useState } from "react";
import { Download, Plus, ScrollText, ShieldCheck } from "lucide-react";
import { useApp } from "../context/AppContext";
import type { RouteId } from "../components/AppLayout";
import type { PrivacyRequest } from "../types";
import { Modal } from "../components/Modal";
import { EmptyState, Pagination, TableToolbar } from "../components/TableTools";
import { exportToXlsx } from "../lib/export";

const PAGE_SIZE = 15;
export function AuditPrivacyPage({ initialTab }: { initialTab: Extract<RouteId, "audit" | "privacy"> }) {
  const { data, visible, createRecord, updateRecord, can } = useApp();
  const [tab, setTab] = useState(initialTab);
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState({ personId: "", type: "Acesso" as PrivacyRequest["type"], request: "", assigneeId: "" });
  const [toast, setToast] = useState("");
  const audit = visible(data.audit).filter((item) => !search || `${item.summary} ${item.module} ${item.action}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  const privacy = visible(data.privacyRequests).filter((item) => !search || `${item.type} ${item.request} ${item.status}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  const rows = tab === "audit" ? audit : privacy;
  const paged = rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  const submit = async (event: React.FormEvent) => { event.preventDefault(); await createRecord("privacyRequests", { ...form, status: "Nova", result: "" }, `Solicitação de privacidade ${form.type} criada`); setFormOpen(false); setToast("Solicitação registrada e incluída no workflow."); setTimeout(() => setToast(""), 2500); };
  const doExport = async () => { if (tab === "audit") exportToXlsx("auditoria", "Auditoria", audit.map((item) => ({ Data: new Date(item.createdAt).toLocaleString("pt-BR"), Usuário: data.users.find((user) => user.id === item.createdBy)?.name ?? "Sistema", Ação: item.action, Módulo: item.module, Resumo: item.summary, Dispositivo: item.deviceId }))); else exportToXlsx("solicitacoes-privacidade", "Privacidade", privacy.map((item) => ({ Tipo: item.type, Pessoa: data.people.find((person) => person.id === item.personId)?.name ?? "", Status: item.status, Solicitação: item.request, Data: new Date(item.createdAt).toLocaleString("pt-BR") }))); await createRecord("audit", { action: "export", module: tab, summary: `Exportação de ${rows.length} registros`, deviceId: localStorage.getItem("central-campanha-device") ?? "browser" }); };

  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">GOVERNANÇA E LGPD</p><h1>Auditoria e Privacidade</h1><p>Rastreabilidade de ações e atendimento aos direitos dos titulares.</p></div>{tab === "privacy" && can("privacy", "create") && <button className="button primary" onClick={() => setFormOpen(true)}><Plus size={18} /> Nova solicitação</button>}</header><div className="section-tabs"><button className={tab === "privacy" ? "active" : ""} onClick={() => { setTab("privacy"); setPage(1); }}><ShieldCheck size={17} /> Privacidade</button><button className={tab === "audit" ? "active" : ""} onClick={() => { setTab("audit"); setPage(1); }}><ScrollText size={17} /> Auditoria</button></div>
    <section className="panel table-panel"><TableToolbar search={search} onSearch={setSearch} placeholder={tab === "audit" ? "Buscar por ação, módulo ou resumo" : "Buscar solicitações"} onExport={can(tab, "export") ? () => void doExport() : undefined} />{rows.length === 0 ? <EmptyState icon={tab === "audit" ? <ScrollText size={38} /> : <ShieldCheck size={38} />} title={tab === "audit" ? "Nenhuma ação registrada" : "Nenhuma solicitação de titular"} description={tab === "audit" ? "Ações críticas aparecem aqui automaticamente e não podem ser editadas por usuários comuns." : "Registre pedidos de acesso, correção, exclusão ou não contato."} /> : <div className="responsive-table"><table><thead><tr>{tab === "audit" ? <><th>Data e hora</th><th>Usuário</th><th>Ação</th><th>Módulo</th><th>Resumo</th><th>Dispositivo</th></> : <><th>Pessoa</th><th>Tipo</th><th>Solicitação</th><th>Status</th><th>Responsável</th></>}</tr></thead><tbody>{tab === "audit" ? paged.map((raw) => { const item = raw as (typeof data.audit)[number]; return <tr key={item.id}><td>{new Date(item.createdAt).toLocaleString("pt-BR")}</td><td>{data.users.find((user) => user.id === item.createdBy)?.name ?? "Sistema"}</td><td><span className="status-badge">{item.action}</span></td><td>{item.module}</td><td>{item.summary}</td><td>{item.deviceId.slice(0, 12)}…</td></tr>; }) : paged.map((raw) => { const item = raw as PrivacyRequest; return <tr key={item.id}><td>{data.people.find((person) => person.id === item.personId)?.name ?? "Não vinculada"}</td><td>{item.type}</td><td>{item.request}</td><td><select value={item.status} onChange={(event) => void updateRecord("privacyRequests", item.id, { status: event.target.value as PrivacyRequest["status"] }, `Solicitação de privacidade movida para ${event.target.value}`)}>{["Nova", "Em análise", "Em processamento", "Concluída"].map((status) => <option key={status}>{status}</option>)}</select></td><td>{data.users.find((user) => user.id === item.assigneeId)?.name ?? "Não atribuído"}</td></tr>; })}</tbody></table></div>}<Pagination page={page} pageSize={PAGE_SIZE} total={rows.length} onPage={setPage} /></section>
    {formOpen && <Modal title="Nova solicitação de titular" description="O atendimento terá histórico e responsável." onClose={() => setFormOpen(false)}><form className="record-form" onSubmit={submit}><div className="form-grid"><label className="span-2">Pessoa<select value={form.personId} onChange={(event) => setForm({ ...form, personId: event.target.value })}><option value="">Não vinculada</option>{data.people.filter((item) => !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Tipo<select value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value as PrivacyRequest["type"] })}>{["Acesso", "Correção", "Exclusão", "Não contato", "Outro"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Responsável<select value={form.assigneeId} onChange={(event) => setForm({ ...form, assigneeId: event.target.value })}><option value="">Não atribuído</option>{data.users.filter((item) => item.active && !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="span-2">Solicitação *<textarea required rows={5} value={form.request} onChange={(event) => setForm({ ...form, request: event.target.value })} /></label></div><footer className="modal-actions"><button type="button" className="button ghost" onClick={() => setFormOpen(false)}>Cancelar</button><button className="button primary">Registrar solicitação</button></footer></form></Modal>}
    {toast && <div className="toast success">{toast}</div>}
  </div>;
}
