import { useEffect, useMemo, useState } from "react";
import { Activity, CalendarDays, CircleDollarSign, Download, FileText, Globe2, Plus, Trash2, Users } from "lucide-react";
import { useApp } from "../context/AppContext";
import type { RouteId } from "../components/AppLayout";
import { ConfirmDialog, Modal } from "../components/Modal";
import { EmptyState, Pagination, TableToolbar } from "../components/TableTools";
import { exportToXlsx } from "../lib/export";
import { readBlob, storeBlob } from "../lib/db";

type Module = Extract<RouteId, "calendar" | "events" | "team" | "territory" | "documents" | "finance" | "reminders">;
const PAGE_SIZE = 12;
const configs = {
  calendar: { eyebrow: "TEMPO E PRIORIDADES", title: "Agenda", description: "Compromissos, participantes e alertas de conflito.", singular: "compromisso", icon: CalendarDays },
  events: { eyebrow: "OPERAÇÃO EM CAMPO", title: "Eventos", description: "Planejamento, equipe, checklist e resultado operacional.", singular: "evento", icon: Activity },
  team: { eyebrow: "PESSOAS DA OPERAÇÃO", title: "Equipe e Voluntários", description: "Funções, disponibilidade e alocação territorial.", singular: "integrante", icon: Users },
  territory: { eyebrow: "COBERTURA OPERACIONAL", title: "Território", description: "Estados, municípios, bairros e regiões configuráveis.", singular: "território", icon: Globe2 },
  documents: { eyebrow: "ARQUIVOS AUTORIZADOS", title: "Documentos", description: "Documentos locais na fila, com categoria e nível de acesso.", singular: "documento", icon: FileText },
  finance: { eyebrow: "CONTROLE AUXILIAR", title: "Administrativo / Financeiro", description: "Apoio operacional; não substitui a prestação oficial de contas.", singular: "despesa", icon: CircleDollarSign },
  reminders: { eyebrow: "ACOMPANHAMENTO", title: "Lembretes", description: "Retornos, prazos e avisos importantes.", singular: "lembrete", icon: CalendarDays },
} as const;

const initialForms: Record<Module, Record<string, string | boolean>> = {
  calendar: { title: "", type: "Reunião", description: "", startAt: "", endAt: "", location: "", address: "", territoryId: "", assigneeId: "", notes: "" },
  events: { name: "", description: "", startAt: "", endAt: "", address: "", territoryId: "", neighborhood: "", assigneeId: "", internalBudget: "", status: "Planejamento", checklist: "" },
  team: { name: "", role: "Voluntário", territoryId: "", availability: "", assigneeId: "", team: "", status: "Ativo", notes: "" },
  territory: { name: "", type: "Município", parentId: "", stateCode: "" },
  documents: { name: "", description: "", category: "Administrativo", tags: "", assigneeId: "", relatedType: "", relatedId: "", accessLevel: "Geral" },
  finance: { description: "", category: "Administrativo", supplier: "", amount: "", date: new Date().toISOString().slice(0, 10), paymentMethod: "", assigneeId: "", eventId: "", costCenter: "", notes: "" },
  reminders: { title: "", type: "Lembrete manual", dueAt: "", assigneeId: "", done: false },
};

export function OperationsPage({ module }: { module: Module }) {
  const config = configs[module];
  const { data, visible, createRecord, updateRecord, softDelete, can, currentUser } = useApp();
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState<Record<string, string | boolean>>({ ...initialForms[module] });
  const [file, setFile] = useState<File | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<{ id: string; label: string } | null>(null);
  const [calendarView, setCalendarView] = useState<"day" | "week" | "month" | "list">("list");
  const [toast, setToast] = useState("");

  useEffect(() => { setForm({ ...initialForms[module] }); setSearch(""); setPage(1); }, [module]);
  useEffect(() => { const listener = (event: Event) => { if ((event as CustomEvent).detail === module) openCreate(); }; window.addEventListener("central:quick-new", listener); return () => window.removeEventListener("central:quick-new", listener); }, [module]);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(""), 2600); return () => clearTimeout(timer); }, [toast]);
  const openCreate = () => { setForm({ ...initialForms[module] }); setFile(null); setFormOpen(true); };

  const rows = useMemo(() => {
    const term = search.toLocaleLowerCase("pt-BR");
    if (module === "calendar") return visible(data.calendar).filter((item) => `${item.title} ${item.type} ${item.location}`.toLocaleLowerCase("pt-BR").includes(term));
    if (module === "events") return visible(data.events).filter((item) => `${item.name} ${item.status}`.toLocaleLowerCase("pt-BR").includes(term));
    if (module === "team") return visible(data.team).filter((item) => `${item.name} ${item.role} ${item.team}`.toLocaleLowerCase("pt-BR").includes(term));
    if (module === "territory") return visible(data.territories).filter((item) => `${item.name} ${item.type}`.toLocaleLowerCase("pt-BR").includes(term));
    if (module === "documents") return visible(data.documents).filter((item) => `${item.name} ${item.category} ${item.tags.join(" ")}`.toLocaleLowerCase("pt-BR").includes(term));
    if (module === "finance") return visible(data.expenses).filter((item) => `${item.description} ${item.category} ${item.supplier}`.toLocaleLowerCase("pt-BR").includes(term));
    return visible(data.reminders).filter((item) => `${item.title} ${item.type}`.toLocaleLowerCase("pt-BR").includes(term));
  }, [data, module, search, visible]);

  const paged = rows.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);
  const field = (name: string) => String(form[name] ?? "");
  const set = (name: string, value: string | boolean) => setForm((previous) => ({ ...previous, [name]: value }));
  const calendarConflicts = module === "calendar" && field("startAt") && field("endAt") ? data.calendar.filter((item) => !item.deletedAt && item.assigneeId === field("assigneeId") && new Date(item.startAt) < new Date(field("endAt")) && new Date(item.endAt) > new Date(field("startAt"))) : [];

  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (module === "calendar") await createRecord("calendar", { title: field("title"), type: field("type"), description: field("description"), startAt: new Date(field("startAt")).toISOString(), endAt: new Date(field("endAt")).toISOString(), location: field("location"), address: field("address"), territoryId: field("territoryId"), participants: [], assigneeId: field("assigneeId"), notes: field("notes") }, `Compromisso ${field("title")} criado`);
    if (module === "events") await createRecord("events", { name: field("name"), description: field("description"), startAt: new Date(field("startAt")).toISOString(), endAt: field("endAt") ? new Date(field("endAt")).toISOString() : undefined, address: field("address"), territoryId: field("territoryId"), neighborhood: field("neighborhood"), assigneeId: field("assigneeId"), team: [], suppliers: [], internalBudget: Number(field("internalBudget") || 0), status: field("status") as "Planejamento", checklist: field("checklist").split("\n").filter(Boolean).map((text) => ({ id: crypto.randomUUID(), text, done: false })) }, `Evento ${field("name")} criado`);
    if (module === "team") await createRecord("team", { name: field("name"), role: field("role"), territoryId: field("territoryId"), availability: field("availability"), assigneeId: field("assigneeId"), team: field("team"), status: field("status") as "Ativo", notes: field("notes") }, `Integrante ${field("name")} cadastrado`);
    if (module === "territory") await createRecord("territories", { name: field("name"), type: field("type") as "Município", parentId: field("parentId"), stateCode: field("stateCode").toUpperCase() }, `Território ${field("name")} cadastrado`);
    if (module === "documents") {
      const blobId = file ? crypto.randomUUID() : undefined; if (file && blobId) await storeBlob(blobId, file);
      await createRecord("documents", { name: field("name") || file?.name || "Documento", description: field("description"), category: field("category"), tags: field("tags").split(",").map((item) => item.trim()).filter(Boolean), assigneeId: field("assigneeId"), relatedType: field("relatedType"), relatedId: field("relatedId"), size: file?.size, mimeType: file?.type, localBlobId: blobId, accessLevel: field("accessLevel") as "Geral" }, `Documento ${field("name") || file?.name} adicionado`);
    }
    if (module === "finance") await createRecord("expenses", { description: field("description"), category: field("category"), supplier: field("supplier"), amount: Number(field("amount")), date: field("date"), paymentMethod: field("paymentMethod"), assigneeId: field("assigneeId"), eventId: field("eventId"), costCenter: field("costCenter"), notes: field("notes") }, `Despesa ${field("description")} registrada`);
    if (module === "reminders") await createRecord("reminders", { title: field("title"), type: field("type"), dueAt: new Date(field("dueAt")).toISOString(), assigneeId: field("assigneeId") || currentUser?.id, done: false }, `Lembrete ${field("title")} criado`);
    setFormOpen(false); setToast(`${config.singular[0].toUpperCase()}${config.singular.slice(1)} salvo e disponível offline.`);
  };

  const doExport = async () => {
    const mapped = rows.map((row) => {
      if (module === "calendar") { const item = row as (typeof data.calendar)[number]; return { Título: item.title, Tipo: item.type, Início: new Date(item.startAt).toLocaleString("pt-BR"), Fim: new Date(item.endAt).toLocaleString("pt-BR"), Local: item.location }; }
      if (module === "events") { const item = row as (typeof data.events)[number]; return { Evento: item.name, Status: item.status, Data: new Date(item.startAt).toLocaleString("pt-BR"), Endereço: item.address, Orçamento: item.internalBudget }; }
      if (module === "team") { const item = row as (typeof data.team)[number]; return { Nome: item.name, Função: item.role, Status: item.status, Equipe: item.team, Disponibilidade: item.availability }; }
      if (module === "territory") { const item = row as (typeof data.territories)[number]; return { Nome: item.name, Tipo: item.type, UF: item.stateCode }; }
      if (module === "documents") { const item = row as (typeof data.documents)[number]; return { Documento: item.name, Categoria: item.category, Acesso: item.accessLevel, Tags: item.tags.join(", "), Data: new Date(item.createdAt).toLocaleDateString("pt-BR") }; }
      if (module === "finance") { const item = row as (typeof data.expenses)[number]; return { Descrição: item.description, Categoria: item.category, Fornecedor: item.supplier, Valor: item.amount, Data: new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR"), "Centro de custo": item.costCenter }; }
      const item = row as (typeof data.reminders)[number]; return { Lembrete: item.title, Tipo: item.type, Data: new Date(item.dueAt).toLocaleString("pt-BR"), Concluído: item.done ? "Sim" : "Não" };
    });
    exportToXlsx(`${module}-central-campanha`, config.title, mapped); await createRecord("audit", { action: "export", module, summary: `Exportação de ${rows.length} registros`, deviceId: localStorage.getItem("central-campanha-device") ?? "browser" }); setToast("Exportação XLSX concluída.");
  };

  const downloadDocument = async (id: string, name: string, blobId?: string) => { if (!blobId) return; const blob = await readBlob(blobId); if (!blob) return; const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = name; anchor.click(); URL.revokeObjectURL(url); await createRecord("audit", { action: "download", module: "documents", recordId: id, summary: `Documento ${name} baixado`, deviceId: localStorage.getItem("central-campanha-device") ?? "browser" }); };

  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">{config.eyebrow}</p><h1>{config.title}</h1><p>{config.description}</p></div><div className="header-actions">{module === "calendar" && <div className="segmented calendar-views">{(["day", "week", "month", "list"] as const).map((view) => <button key={view} className={calendarView === view ? "active" : ""} onClick={() => setCalendarView(view)}>{{ day: "Dia", week: "Semana", month: "Mês", list: "Lista" }[view]}</button>)}</div>}{can(module, "create") && <button className="button primary" onClick={openCreate}><Plus size={18} /> Novo {config.singular}</button>}</div></header>
    <section className="panel table-panel"><TableToolbar search={search} onSearch={setSearch} placeholder={`Buscar em ${config.title.toLocaleLowerCase("pt-BR")}`} onExport={can(module, "export") ? () => void doExport() : undefined} />{rows.length === 0 ? <EmptyState icon={<config.icon size={38} />} title={`Nenhum ${config.singular} cadastrado`} description={`Use “Novo ${config.singular}” para iniciar esta área da operação.`} action={can(module, "create") ? <button className="button primary" onClick={openCreate}><Plus size={17} /> Novo {config.singular}</button> : undefined} /> : <div className="responsive-table"><table><thead><tr>{tableHeaders(module).map((header) => <th key={header}>{header}</th>)}<th /></tr></thead><tbody>{paged.map((row) => <tr key={row.id}>{tableCells(module, row, data).map((cell, index) => <td key={index}>{cell}</td>)}<td><div className="row-actions">{module === "documents" && <button className="icon-button" title="Baixar" disabled={!(row as (typeof data.documents)[number]).localBlobId} onClick={() => void downloadDocument(row.id, (row as (typeof data.documents)[number]).name, (row as (typeof data.documents)[number]).localBlobId)}><Download size={17} /></button>} {module === "reminders" && <button className="button tiny" onClick={() => void updateRecord("reminders", row.id, { done: !(row as (typeof data.reminders)[number]).done })}>{(row as (typeof data.reminders)[number]).done ? "Reabrir" : "Concluir"}</button>}<button className="icon-button danger-icon" onClick={() => setDeleteTarget({ id: row.id, label: String((row as { name?: string; title?: string; description?: string }).name ?? (row as { title?: string }).title ?? (row as { description?: string }).description ?? config.singular) })}><Trash2 size={16} /></button></div></td></tr>)}</tbody></table></div>}<Pagination page={page} pageSize={PAGE_SIZE} total={rows.length} onPage={setPage} /></section>
    {formOpen && <Modal title={`Novo ${config.singular}`} description={module === "documents" ? "O arquivo fica armazenado localmente até a sincronização ser confirmada." : "Os dados serão salvos neste dispositivo mesmo sem conexão."} onClose={() => setFormOpen(false)} wide><form className="record-form" onSubmit={submit}>{renderForm(module, form, set, data, file, setFile)}{calendarConflicts.length > 0 && <div className="duplicate-warning"><CalendarDays size={20} /><div><strong>Possível conflito de agenda</strong><p>{calendarConflicts.map((item) => item.title).join(", ")} já ocupa parte deste horário. Você pode continuar se desejar.</p></div></div>}<footer className="modal-actions"><button type="button" className="button ghost" onClick={() => setFormOpen(false)}>Cancelar</button><button className="button primary">Salvar {config.singular}</button></footer></form></Modal>}
    {deleteTarget && <ConfirmDialog title={`Mover ${config.singular} para a lixeira?`} message={`${deleteTarget.label} deixará de aparecer nas listagens, mas poderá ser restaurado e a ação será auditada.`} danger confirmLabel="Mover para lixeira" onClose={() => setDeleteTarget(null)} onConfirm={async () => { const collection = ({ calendar: "calendar", events: "events", team: "team", territory: "territories", documents: "documents", finance: "expenses", reminders: "reminders" } as const)[module]; await softDelete(collection, deleteTarget.id); setDeleteTarget(null); setToast("Registro movido para a lixeira."); }} />}
    {toast && <div className="toast success">{toast}</div>}
  </div>;
}

function tableHeaders(module: Module) { return ({ calendar: ["Compromisso", "Tipo", "Início", "Local"], events: ["Evento", "Status", "Data", "Território", "Orçamento"], team: ["Nome", "Função", "Status", "Território"], territory: ["Território", "Tipo", "Pertence a", "Indicadores"], documents: ["Documento", "Categoria", "Acesso", "Data"], finance: ["Descrição", "Categoria", "Fornecedor", "Valor", "Data"], reminders: ["Lembrete", "Tipo", "Quando", "Status"] } as const)[module]; }
function tableCells(module: Module, row: { id: string }, data: ReturnType<typeof useApp>["data"]): React.ReactNode[] {
  if (module === "calendar") { const item = row as (typeof data.calendar)[number]; return [<strong>{item.title}</strong>, item.type, new Date(item.startAt).toLocaleString("pt-BR"), item.location || "—"]; }
  if (module === "events") { const item = row as (typeof data.events)[number]; return [<strong>{item.name}</strong>, <span className="status-badge">{item.status}</span>, new Date(item.startAt).toLocaleString("pt-BR"), data.territories.find((territory) => territory.id === item.territoryId)?.name ?? "—", (item.internalBudget ?? 0).toLocaleString("pt-BR", { style: "currency", currency: "BRL" })]; }
  if (module === "team") { const item = row as (typeof data.team)[number]; return [<strong>{item.name}</strong>, item.role, <span className="status-badge">{item.status}</span>, data.territories.find((territory) => territory.id === item.territoryId)?.name ?? "—"]; }
  if (module === "territory") { const item = row as (typeof data.territories)[number]; const indicators = data.activities.filter((activity) => activity.territoryId === item.id).length + data.events.filter((event) => event.territoryId === item.id).length; return [<strong>{item.name}</strong>, item.type, data.territories.find((territory) => territory.id === item.parentId)?.name ?? item.stateCode ?? "—", `${indicators} atividades/eventos`]; }
  if (module === "documents") { const item = row as (typeof data.documents)[number]; return [<strong>{item.name}</strong>, item.category, <span className="status-badge">{item.accessLevel}</span>, new Date(item.createdAt).toLocaleDateString("pt-BR")]; }
  if (module === "finance") { const item = row as (typeof data.expenses)[number]; return [<strong>{item.description}</strong>, item.category, item.supplier || "—", item.amount.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }), new Date(`${item.date}T12:00:00`).toLocaleDateString("pt-BR")]; }
  const item = row as (typeof data.reminders)[number]; return [<strong>{item.title}</strong>, item.type, new Date(item.dueAt).toLocaleString("pt-BR"), <span className="status-badge">{item.done ? "Concluído" : "Pendente"}</span>];
}

function renderForm(module: Module, form: Record<string, string | boolean>, set: (name: string, value: string | boolean) => void, data: ReturnType<typeof useApp>["data"], file: File | null, setFile: (file: File | null) => void) {
  const value = (name: string) => String(form[name] ?? "");
  const territories = <><option value="">Não informado</option>{data.territories.filter((item) => !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.name} — {item.type}</option>)}</>;
  const users = <><option value="">Não atribuído</option>{data.users.filter((item) => item.active && !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</>;
  if (module === "calendar") return <div className="form-grid"><label className="span-2">Título *<input required value={value("title")} onChange={(e) => set("title", e.target.value)} /></label><label>Tipo<select value={value("type")} onChange={(e) => set("type", e.target.value)}>{["Reunião", "Entrevista", "Evento", "Visita", "Gravação", "Viagem", "Atividade interna", "Compromisso jurídico", "Outro"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Responsável<select value={value("assigneeId")} onChange={(e) => set("assigneeId", e.target.value)}>{users}</select></label><label>Início *<input required type="datetime-local" value={value("startAt")} onChange={(e) => set("startAt", e.target.value)} /></label><label>Fim *<input required type="datetime-local" value={value("endAt")} onChange={(e) => set("endAt", e.target.value)} /></label><label>Local<input value={value("location")} onChange={(e) => set("location", e.target.value)} /></label><label>Território<select value={value("territoryId")} onChange={(e) => set("territoryId", e.target.value)}>{territories}</select></label><label className="span-2">Endereço<input value={value("address")} onChange={(e) => set("address", e.target.value)} /></label><label className="span-2">Descrição<textarea rows={3} value={value("description")} onChange={(e) => set("description", e.target.value)} /></label></div>;
  if (module === "events") return <div className="form-grid"><label className="span-2">Nome do evento *<input required value={value("name")} onChange={(e) => set("name", e.target.value)} /></label><label>Início *<input required type="datetime-local" value={value("startAt")} onChange={(e) => set("startAt", e.target.value)} /></label><label>Fim<input type="datetime-local" value={value("endAt")} onChange={(e) => set("endAt", e.target.value)} /></label><label>Status<select value={value("status")} onChange={(e) => set("status", e.target.value)}>{["Planejamento", "Confirmado", "Em andamento", "Realizado", "Cancelado"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Responsável<select value={value("assigneeId")} onChange={(e) => set("assigneeId", e.target.value)}>{users}</select></label><label>Território<select value={value("territoryId")} onChange={(e) => set("territoryId", e.target.value)}>{territories}</select></label><label>Bairro / Região<input value={value("neighborhood")} onChange={(e) => set("neighborhood", e.target.value)} /></label><label className="span-2">Endereço<input value={value("address")} onChange={(e) => set("address", e.target.value)} /></label><label>Orçamento interno (R$)<input type="number" min="0" step="0.01" value={value("internalBudget")} onChange={(e) => set("internalBudget", e.target.value)} /></label><label className="span-2">Checklist <small>um item por linha</small><textarea rows={4} value={value("checklist")} onChange={(e) => set("checklist", e.target.value)} /></label><label className="span-2">Descrição<textarea rows={3} value={value("description")} onChange={(e) => set("description", e.target.value)} /></label></div>;
  if (module === "team") return <div className="form-grid"><label className="span-2">Nome *<input required value={value("name")} onChange={(e) => set("name", e.target.value)} /></label><label>Função<input required value={value("role")} onChange={(e) => set("role", e.target.value)} /></label><label>Status<select value={value("status")} onChange={(e) => set("status", e.target.value)}>{["Ativo", "Temporariamente indisponível", "Inativo"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Território<select value={value("territoryId")} onChange={(e) => set("territoryId", e.target.value)}>{territories}</select></label><label>Equipe<input value={value("team")} onChange={(e) => set("team", e.target.value)} /></label><label className="span-2">Disponibilidade<input value={value("availability")} onChange={(e) => set("availability", e.target.value)} placeholder="Ex.: terças e quintas, 18h às 22h" /></label><label className="span-2">Observações<textarea rows={3} value={value("notes")} onChange={(e) => set("notes", e.target.value)} /></label></div>;
  if (module === "territory") return <div className="form-grid"><label className="span-2">Nome *<input required value={value("name")} onChange={(e) => set("name", e.target.value)} /></label><label>Tipo<select value={value("type")} onChange={(e) => set("type", e.target.value)}>{["Estado", "Município", "Bairro/Região"].map((item) => <option key={item}>{item}</option>)}</select></label><label>UF<input maxLength={2} value={value("stateCode")} onChange={(e) => set("stateCode", e.target.value)} /></label><label className="span-2">Pertence a<select value={value("parentId")} onChange={(e) => set("parentId", e.target.value)}>{territories}</select></label></div>;
  if (module === "documents") return <div className="form-grid"><label className="span-2 upload-compact">Arquivo *<input required type="file" onChange={(e) => { const next = e.target.files?.[0] ?? null; setFile(next); if (next && !value("name")) set("name", next.name); }} />{file && <span>{file.name} • {(file.size / 1024).toFixed(1)} KB</span>}</label><label className="span-2">Nome<input value={value("name")} onChange={(e) => set("name", e.target.value)} /></label><label>Categoria<select value={value("category")} onChange={(e) => set("category", e.target.value)}>{["Administrativo", "Jurídico", "Contabilidade", "Eventos", "Contratos", "Fornecedores", "Relatórios", "Comunicação", "Outros"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Nível de acesso<select value={value("accessLevel")} onChange={(e) => set("accessLevel", e.target.value)}>{["Geral", "Restrito", "Jurídico", "Financeiro"].map((item) => <option key={item}>{item}</option>)}</select></label><label className="span-2">Tags<input value={value("tags")} onChange={(e) => set("tags", e.target.value)} /></label><label className="span-2">Descrição<textarea rows={3} value={value("description")} onChange={(e) => set("description", e.target.value)} /></label></div>;
  if (module === "finance") return <div className="form-grid"><label className="span-2">Descrição *<input required value={value("description")} onChange={(e) => set("description", e.target.value)} /></label><label>Categoria<input required value={value("category")} onChange={(e) => set("category", e.target.value)} /></label><label>Fornecedor<input value={value("supplier")} onChange={(e) => set("supplier", e.target.value)} /></label><label>Valor (R$) *<input required type="number" min="0" step="0.01" value={value("amount")} onChange={(e) => set("amount", e.target.value)} /></label><label>Data *<input required type="date" value={value("date")} onChange={(e) => set("date", e.target.value)} /></label><label>Forma de pagamento<input value={value("paymentMethod")} onChange={(e) => set("paymentMethod", e.target.value)} /></label><label>Centro de custo<input value={value("costCenter")} onChange={(e) => set("costCenter", e.target.value)} /></label><label>Evento relacionado<select value={value("eventId")} onChange={(e) => set("eventId", e.target.value)}><option value="">Nenhum</option>{data.events.filter((item) => !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="span-2">Observações<textarea rows={3} value={value("notes")} onChange={(e) => set("notes", e.target.value)} /></label></div>;
  return <div className="form-grid"><label className="span-2">Título *<input required value={value("title")} onChange={(e) => set("title", e.target.value)} /></label><label>Tipo<select value={value("type")} onChange={(e) => set("type", e.target.value)}>{["Tarefa vencendo", "Tarefa atrasada", "Processo sem atualização", "Retorno prometido", "Evento próximo", "Compromisso", "Documento", "Lembrete manual"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Responsável<select value={value("assigneeId")} onChange={(e) => set("assigneeId", e.target.value)}>{users}</select></label><label className="span-2">Quando *<input required type="datetime-local" value={value("dueAt")} onChange={(e) => set("dueAt", e.target.value)} /></label></div>;
}
