import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, ClipboardCheck, GripVertical, List, MoreHorizontal, Plus, Send, Trello, Trash2 } from "lucide-react";
import { useApp } from "../context/AppContext";
import type { Priority, TaskRecord } from "../types";
import { ConfirmDialog, Modal } from "../components/Modal";
import { EmptyState, Pagination, TableToolbar } from "../components/TableTools";
import { exportToXlsx } from "../lib/export";

const statuses: TaskRecord["status"][] = ["A fazer", "Em andamento", "Aguardando", "Concluído"];
const priorities: Priority[] = ["Baixa", "Normal", "Alta", "Urgente"];
const emptyForm = { title: "", description: "", assigneeId: "", team: "", priority: "Normal" as Priority, status: "A fazer" as TaskRecord["status"], dueDate: "", checklistText: "", processId: "", eventId: "", personId: "", reminderAt: "" };
const PAGE_SIZE = 12;

export function TasksPage({ onlyMine = false }: { onlyMine?: boolean }) {
  const { data, visible, createRecord, updateRecord, softDelete, can, currentUser } = useApp();
  const [view, setView] = useState<"list" | "kanban">("kanban");
  const [search, setSearch] = useState("");
  const [page, setPage] = useState(1);
  const [formOpen, setFormOpen] = useState(false);
  const [form, setForm] = useState(emptyForm);
  const [editing, setEditing] = useState<TaskRecord | null>(null);
  const [selected, setSelected] = useState<TaskRecord | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<TaskRecord | null>(null);
  const [comment, setComment] = useState("");
  const [toast, setToast] = useState("");
  const baseTasks = visible(data.tasks).filter((item) => !onlyMine || item.assigneeId === currentUser?.id);
  const tasks = baseTasks.filter((item) => !search || `${item.title} ${item.description ?? ""}`.toLocaleLowerCase("pt-BR").includes(search.toLocaleLowerCase("pt-BR")));
  const paged = tasks.slice((page - 1) * PAGE_SIZE, page * PAGE_SIZE);

  useEffect(() => { const listener = (event: Event) => { if ((event as CustomEvent).detail === "tasks") openCreate(); }; window.addEventListener("central:quick-new", listener); return () => window.removeEventListener("central:quick-new", listener); }, []);
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(""), 2500); return () => clearTimeout(timer); }, [toast]);
  function openCreate() { setEditing(null); setForm({ ...emptyForm, assigneeId: onlyMine ? currentUser?.id ?? "" : "" }); setFormOpen(true); }
  function openEdit(item: TaskRecord) { setEditing(item); setForm({ title: item.title, description: item.description ?? "", assigneeId: item.assigneeId ?? "", team: item.team ?? "", priority: item.priority, status: item.status, dueDate: item.dueDate ?? "", checklistText: item.checklist.map((entry) => entry.text).join("\n"), processId: item.processId ?? "", eventId: item.eventId ?? "", personId: item.personId ?? "", reminderAt: item.reminderAt ?? "" }); setFormOpen(true); }
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); const checklist = form.checklistText.split("\n").map((text, index) => text.trim() ? ({ id: editing?.checklist[index]?.id ?? crypto.randomUUID(), text: text.trim(), done: editing?.checklist[index]?.done ?? false }) : null).filter(Boolean) as TaskRecord["checklist"];
    const { checklistText: _, ...payload } = form; const assigneeChanged = form.assigneeId && form.assigneeId !== editing?.assigneeId;
    if (editing) await updateRecord("tasks", editing.id, { ...payload, checklist }, `Tarefa ${form.title} atualizada`); else await createRecord("tasks", { ...payload, checklist }, `Tarefa ${form.title} criada`);
    if (assigneeChanged) await createRecord("notifications", { title: "Nova tarefa atribuída", message: form.title, recipientId: form.assigneeId, relatedType: "tasks", relatedId: editing?.id });
    setFormOpen(false); setToast(editing ? "Tarefa atualizada." : "Tarefa criada e atribuída.");
  };
  const moveTask = async (id: string, status: TaskRecord["status"]) => { await updateRecord("tasks", id, { status }, `Tarefa movida para ${status}`); setToast(`Tarefa movida para ${status}.`); };
  const toggleChecklist = async (task: TaskRecord, id: string) => { const checklist = task.checklist.map((item) => item.id === id ? { ...item, done: !item.done } : item); await updateRecord("tasks", task.id, { checklist }, "Checklist da tarefa atualizado"); setSelected({ ...task, checklist }); };
  const addComment = async () => { if (!selected || !comment.trim()) return; await createRecord("comments", { module: "tasks", recordId: selected.id, body: comment.trim(), mentions: [] }, `Comentário adicionado à tarefa ${selected.title}`); setComment(""); };
  const doExport = async () => { exportToXlsx("tarefas", "Tarefas", tasks.map((item) => ({ Título: item.title, Status: item.status, Prioridade: item.priority, Responsável: data.users.find((user) => user.id === item.assigneeId)?.name ?? "", Prazo: item.dueDate ? new Date(`${item.dueDate}T12:00:00`).toLocaleDateString("pt-BR") : "", Checklist: `${item.checklist.filter((check) => check.done).length}/${item.checklist.length}` }))); await createRecord("audit", { action: "export", module: "tasks", summary: `Exportação de ${tasks.length} tarefas`, deviceId: localStorage.getItem("central-campanha-device") ?? "browser" }); setToast("Tarefas exportadas."); };

  return <div className="page-stack"><header className="page-header"><div><p className="eyebrow">EXECUÇÃO</p><h1>{onlyMine ? "Minhas Pendências" : "Tarefas"}</h1><p>{onlyMine ? "Tudo o que depende de você, ordenado para agir." : "Planeje, atribua e acompanhe a execução da equipe."}</p></div><div className="header-actions"><div className="segmented"><button className={view === "list" ? "active" : ""} onClick={() => setView("list")}><List size={16} /> Lista</button><button className={view === "kanban" ? "active" : ""} onClick={() => setView("kanban")}><Trello size={16} /> Kanban</button></div>{can("tasks", "create") && <button className="button primary" onClick={openCreate}><Plus size={18} /> Nova tarefa</button>}</div></header>
    <section className="panel table-panel"><TableToolbar search={search} onSearch={setSearch} placeholder="Buscar tarefas" onExport={can("tasks", "export") ? () => void doExport() : undefined} />
      {tasks.length === 0 ? <EmptyState icon={<ClipboardCheck size={38} />} title="Nenhuma tarefa encontrada" description={baseTasks.length === 0 ? "Crie uma tarefa, defina o responsável e acompanhe o progresso por aqui." : "A busca atual não encontrou resultados."} action={can("tasks", "create") && baseTasks.length === 0 ? <button className="button primary" onClick={openCreate}><Plus size={17} /> Nova tarefa</button> : undefined} /> : view === "kanban" ? <div className="kanban-board">{statuses.map((status) => <section key={status} className="kanban-column" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const id = event.dataTransfer.getData("text/task-id"); if (id) void moveTask(id, status); }}><header><span>{status}</span><b>{tasks.filter((item) => item.status === status).length}</b></header><div>{tasks.filter((item) => item.status === status).map((item) => { const done = item.checklist.filter((entry) => entry.done).length; const overdue = item.dueDate && item.status !== "Concluído" && new Date(`${item.dueDate}T23:59:59`) < new Date(); return <article key={item.id} draggable onDragStart={(event) => event.dataTransfer.setData("text/task-id", item.id)} onClick={() => setSelected(item)}><div className="task-card-top"><GripVertical size={15} /><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span></div><h3>{item.title}</h3>{item.dueDate && <span className={overdue ? "due overdue" : "due"}>{overdue && <AlertTriangle size={13} />}{new Date(`${item.dueDate}T12:00:00`).toLocaleDateString("pt-BR")}</span>}{item.checklist.length > 0 && <div className="task-progress"><span><i style={{ width: `${(done / item.checklist.length) * 100}%` }} /></span><small>{done}/{item.checklist.length}</small></div>}<footer><span className="avatar tiny">{data.users.find((user) => user.id === item.assigneeId)?.name.slice(0, 1) ?? "?"}</span><span>{data.users.find((user) => user.id === item.assigneeId)?.name ?? "Não atribuído"}</span></footer></article>; })}</div></section>)}</div> : <div className="responsive-table"><table><thead><tr><th>Tarefa</th><th>Status</th><th>Prioridade</th><th>Responsável</th><th>Prazo</th><th>Progresso</th><th /></tr></thead><tbody>{paged.map((item) => <tr key={item.id} onClick={() => setSelected(item)}><td><strong>{item.title}</strong></td><td><span className="status-badge">{item.status}</span></td><td><span className={`priority priority-${item.priority.toLowerCase()}`}>{item.priority}</span></td><td>{data.users.find((user) => user.id === item.assigneeId)?.name ?? "Não atribuído"}</td><td>{item.dueDate ? new Date(`${item.dueDate}T12:00:00`).toLocaleDateString("pt-BR") : "Sem prazo"}</td><td>{item.checklist.filter((check) => check.done).length}/{item.checklist.length}</td><td><button className="icon-button" onClick={(event) => { event.stopPropagation(); openEdit(item); }}><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></div>}
      {view === "list" && <Pagination page={page} pageSize={PAGE_SIZE} total={tasks.length} onPage={setPage} />}
    </section>
    {formOpen && <Modal title={editing ? "Editar tarefa" : "Nova tarefa"} description="A atribuição gera uma notificação para o responsável." onClose={() => setFormOpen(false)} wide><form className="record-form" onSubmit={submit}><div className="form-grid"><label className="span-2">Título *<input required value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /></label><label className="span-2">Descrição<textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></label><label>Status<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value as TaskRecord["status"] })}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></label><label>Prioridade<select value={form.priority} onChange={(event) => setForm({ ...form, priority: event.target.value as Priority })}>{priorities.map((item) => <option key={item}>{item}</option>)}</select></label><label>Responsável<select value={form.assigneeId} onChange={(event) => setForm({ ...form, assigneeId: event.target.value })}><option value="">Não atribuído</option>{data.users.filter((item) => item.active && !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label>Equipe<input value={form.team} onChange={(event) => setForm({ ...form, team: event.target.value })} /></label><label>Prazo<input type="date" value={form.dueDate} onChange={(event) => setForm({ ...form, dueDate: event.target.value })} /></label><label>Lembrete<input type="datetime-local" value={form.reminderAt} onChange={(event) => setForm({ ...form, reminderAt: event.target.value })} /></label><label>Processo relacionado<select value={form.processId} onChange={(event) => setForm({ ...form, processId: event.target.value })}><option value="">Nenhum</option>{data.processes.filter((item) => !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.code} — {item.title}</option>)}</select></label><label>Evento relacionado<select value={form.eventId} onChange={(event) => setForm({ ...form, eventId: event.target.value })}><option value="">Nenhum</option>{data.events.filter((item) => !item.deletedAt).map((item) => <option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label className="span-2">Checklist <small>um item por linha</small><textarea rows={5} value={form.checklistText} onChange={(event) => setForm({ ...form, checklistText: event.target.value })} placeholder={"Reservar local\nConfirmar equipe\nBuscar material"} /></label></div><footer className="modal-actions"><button type="button" className="button ghost" onClick={() => setFormOpen(false)}>Cancelar</button><button className="button primary">{editing ? "Salvar alterações" : "Criar tarefa"}</button></footer></form></Modal>}
    {selected && <Modal title={selected.title} description={`${selected.priority} • ${data.users.find((user) => user.id === selected.assigneeId)?.name ?? "Não atribuído"}`} onClose={() => setSelected(null)} wide><div className="process-hero"><div><small>Status</small><select value={selected.status} onChange={(event) => { const status = event.target.value as TaskRecord["status"]; void moveTask(selected.id, status); setSelected({ ...selected, status }); }}>{statuses.map((item) => <option key={item}>{item}</option>)}</select></div><div><small>Prazo</small><strong>{selected.dueDate ? new Date(`${selected.dueDate}T12:00:00`).toLocaleDateString("pt-BR") : "Sem prazo"}</strong></div><div><small>Checklist</small><strong>{selected.checklist.filter((item) => item.done).length}/{selected.checklist.length} concluídos</strong></div></div><section className="subsection"><h3>Checklist</h3>{selected.checklist.length === 0 ? <p className="muted">Nenhum item no checklist.</p> : <div className="checklist">{selected.checklist.map((item) => <label key={item.id}><input type="checkbox" checked={item.done} onChange={() => void toggleChecklist(selected, item.id)} /><span>{item.text}</span></label>)}</div>}</section><section className="subsection"><h3>Comentários</h3><div className="comments">{data.comments.filter((item) => item.module === "tasks" && item.recordId === selected.id && !item.deletedAt).map((item) => <div key={item.id}><span className="avatar small">{data.users.find((user) => user.id === item.createdBy)?.name.slice(0, 1) ?? "U"}</span><p><strong>{data.users.find((user) => user.id === item.createdBy)?.name ?? "Usuário"}</strong>{item.body}<small>{new Date(item.createdAt).toLocaleString("pt-BR")}</small></p></div>)}</div><div className="comment-box"><textarea rows={2} value={comment} onChange={(event) => setComment(event.target.value)} placeholder="Adicionar comentário" /><button className="icon-button" disabled={!comment.trim()} onClick={() => void addComment()}><Send size={17} /></button></div></section><footer className="modal-actions split"><button className="button danger-outline" onClick={() => setDeleteTarget(selected)}><Trash2 size={16} /> Mover para lixeira</button><button className="button primary" onClick={() => { openEdit(selected); setSelected(null); }}>Editar tarefa</button></footer></Modal>}
    {deleteTarget && <ConfirmDialog title="Mover tarefa para a lixeira?" message="A tarefa e seu histórico poderão ser restaurados por usuários autorizados." danger confirmLabel="Mover para lixeira" onClose={() => setDeleteTarget(null)} onConfirm={async () => { await softDelete("tasks", deleteTarget.id); setDeleteTarget(null); setSelected(null); setToast("Tarefa movida para a lixeira."); }} />}
    {toast && <div className="toast success">{toast}</div>}
  </div>;
}
